INSERT INTO public.mc_codes (code, program_type) VALUES ('6540', 'POI Funding Transactions (Excluding MoneySend)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6538', 'MoneySend Funding');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6537', 'MoneySend Intercountry');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6536', 'MoneySend Intracountry');
INSERT INTO public.mc_codes (code, program_type) VALUES ('0780', 'Landscaping and Horticultural Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('0763', 'Agricultural Cooperatives');
INSERT INTO public.mc_codes (code, program_type) VALUES ('0742', 'Veterinary Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9950', 'Intra-Company Purchas');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9754', 'Quasi Cash - Gambling-Horse Racing, Dog Racing, State Lotteri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9753', 'Consumer Electronics/Furniture Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9752', 'U.K. Petrol Stations, Electronic Hot Fil');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9751', 'U.K. Supermarkets, Electronic Hot Fil');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9702', 'GCAS Emergency Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9701', 'Visa Credential Serv');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9700', 'Automated Referral Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9405', 'U.S. Fed Government Agenci');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9402', 'Postal Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9401', 'i-Purchasin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9399', 'Government Services - Not Elsewhere Classified');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9311', 'Tax Payment');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9223', 'Bail & Bond Payment');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9222', 'Fin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('9211', 'Court Costs, including Alimony and Child Suppor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8999', 'Professional Services - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8931', 'Accounting, Auditing, and Bookkeeping Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8911', 'Architectural, Engineering, and Surveying Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8734', 'Testing Laboratories (Not Medical) - (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8699', 'Membership Organizations - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8675', 'Automobile Association');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8661', 'Religious Organization');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8651', 'Political Organization');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8641', 'Civic, Social, and Fraternal Association');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8398', 'Charitable and Social Service Organization');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8351', 'Child Care Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8299', 'Schools and Educational Services - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8249', 'Trade and Vocational School');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8244', 'Business and Secretarial School');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8241', 'Correspondence School');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8220', 'Colleges, Universities, Professional Schools, and Junior Colleg');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8211', 'Elementary and Secondary School');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8111', 'Legal Services and Attorney');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8099', 'Medical Services Health Practitioners - No Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8071', 'Medical and Dental Laboratori');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8062', 'Hospital');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8050', 'Nursing and Personal Care Faciliti');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8049', 'Podiatrists and Chiropodist');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8043', 'Opticians, Optical Goods and Eyeglass');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8042', 'Optometrists and Ophthalmologist');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8041', 'Chiropractor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8031', 'Osteopathic Physician');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8021', 'Dentists and Orthodontist');
INSERT INTO public.mc_codes (code, program_type) VALUES ('8011', 'Doctors and Physicians - Not Elsewhere Classified');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7999', 'Recreation Services - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7998', 'Aquarium, Seaquarium, Dolphinarium');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7997', 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Cours');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7996', 'Amusement Parks, Circuses, Carnivals, and Fortune Tellers');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7995', 'Betting, including Lottery Tickets, Casino Gaming Chips, Off- Track Betting, and Wagers at Race Trac');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7994', 'Video Game Arcades and Establishment');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7993', 'Video Amusement Game Suppl');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7992', 'Public Golf Cours');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7991', 'Tourist Attractions and Exhibit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7941', 'Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoter');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7933', 'Bowling Alley');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7932', 'Billiards & Pool Establishment');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7929', 'Bands, Orchestras & Misc Entertainmen');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7922', 'Theatrical Producers (except Motion Pictures) and Ticket Agenci');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7911', 'Dance Halls, Studios & School');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7841', 'DVD/Video Tape Rental Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7832', 'Motion Picture Theat');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7829', 'Motion Picture & Video Tape Production and Distribution (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7802', 'Government-Licensed Horse/Dog Racing ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7801', 'Government-Licensed Casinos (Online Gambling) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7800', 'Government-Owned Lotteries ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7778', 'Citishare Cash Advanc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7699', 'Miscellaneous Repair Shops and Related Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7692', 'Welding Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7641', 'Furniture - Reupholster, Repair, and Refinishin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7631', 'Watch, Clock, and Jewelry Repair Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7629', 'Electrical and Small Appliance Repair Shops');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7623', 'Air Conditioning and Refrigeration Repair Shops');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7622', 'Electronic Repair Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7549', 'Towing Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7542', 'Car Wash');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7538', 'Automotive Service Shops (Non-Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7535', 'Automotive Paint Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7534', 'Tire Retreading & Repai');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7531', 'Automotive Top & Body Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7524', 'Express Payment Service Mechants - Parking Lots and Garag');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7523', 'Parking Lots and Garag');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7519', 'Motor Home and Recreational Vehicle Rental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7513', 'Truck and Utility Trailer Rental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7512', 'Automobile Rental Agenc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7511', 'Truck Stop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7399', 'Business Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7395', 'Photofinishing Laboratories and Photo Developin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7394', 'Equipment, Tool, Furniture, and Appliance Rental and Leasing');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7393', 'Detective Agencies, Protective Agencies, and Security Services, including Armored Cars and Guard Dog');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7392', 'Management, Consulting, and Public Relations Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7379', 'Computer Maintenance, Repair and Services (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7375', 'Information Retrieval Services (Business to Business MCC)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7372', 'Computer Programming, Data Processing, and Integrated Systems Design Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7361', 'Employment Agencies and Temporary Help Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7349', 'Cleaning, Maintenance & Janitorial Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7342', 'Exterminating and Disinfecting Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7339', 'Stenographic Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7338', 'Quick Copy, Reproduction Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7333', 'Commercial Photography, Art, and Graphic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7332', 'Blueprinting and Photocopying Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7321', 'Consumer Credit Reporting Agenci');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7311', 'Advertising Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7299', 'Miscellaneous Personal Services - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7298', 'Health and Beauty Spa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7297', 'Massage Parlor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7296', 'Clothing Rental - Costumes, Uniforms and Formal Wear');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7278', 'Buying and Shopping Services and Club');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7277', 'Counseling Services - Debt, Marriage, and Persona');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7276', 'Tax Preparation Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7273', 'Dating Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7261', 'Funeral Services and Crematori');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7251', 'Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7230', 'Beauty and Barber Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7221', 'Photographic Studio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7217', 'Carpet and Upholstery Cleanin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7216', 'Dry Cleaner');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7211', 'Laundry Services - Family and Commercia');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7210', 'Laundry, Cleaning, and Garment Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7033', 'Trailer Parks and Campground');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7032', 'Sporting and Recreational Camps');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7012', 'Timeshar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('7011', 'Lodging - Hotels, Motels, and Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6535', 'Value Purchase - Member Financial Institutio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6534', 'Money Transfer - Member Financial Institutio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6533', 'Payment Transaction - Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6532', 'Payment Transaction - Memb');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6531', 'Payment Service Provid');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6530', 'Remote Stored Value Load - Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6529', 'Remote Stored Value Load - Member Financial Institutio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6513', 'Real Estate Agents and Managers - Rentals; Property Managemen');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6399', 'Insurance - Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6381', 'Insurance - Premium');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6300', 'Insurance Sales and Underwritin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6211', 'Securities - Brokers and Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6051', 'MasterCard - Quasi Cash-Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6050', 'Quasi Cash - Member Financial Institutio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6012', 'Quasi Cash - Financial Institution - Merchandise and Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6011', 'Financial Institutions--Automated Cash Disbursements');
INSERT INTO public.mc_codes (code, program_type) VALUES ('6010', 'Financial Institutions--Manual Cash Disbursements');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5999', 'Miscellaneous & Specialty Retail Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5998', 'Tent and Awning Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5997', 'Electric Razor Stores Sales & Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5996', 'Swimming Pools--Sales, Supplies, and Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5995', 'Pet Shops, Pet Food, and Suppli');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5994', 'News Dealers & Newsstand');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5993', 'Cigar Stores & Stand');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5992', 'Florist');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5983', 'Fuel Dealers--Fuel Oil, Wood, Coal, and Liquefied Petroleu');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5978', 'Typewriter Stores--Sales, Service, and Rental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5977', 'Cosmetic Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5976', 'Orthopedic Goods and Prosthetic Devic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5975', 'Hearing Aids--Sales, Service, and Suppli');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5973', 'Religious Goods Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5972', 'Stamp and Coin Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5971', 'Art Dealers and Galleri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5970', 'Artist Supply and Craft Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5969', 'Direct Marketing/Direct Marketers--Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5968', 'Continuity/Subscription Merchant');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5967', 'Direct Marketing -- Inbound Telemarketing Merchant');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5966', 'Outbound Telemarketing Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5965', 'Combined Catalog and Retail Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5964', 'Catalog Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5963', 'Direct Selling Establishments/Door to Door Sales');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5962', 'Direct Marketing -- Travel Related Arrangement Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5961', 'Mail Ord');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5960', 'Direct Marketing Insurance Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5950', 'Glassware and Crystal Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5949', 'Sewing, Needlework, Fabric, and Piece Good Stores');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5948', 'Luggage and Leather Goods Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5947', 'Gift, Card, Novelty, and Souvenir Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5946', 'Camera and Photographic Supply Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5945', 'Hobby, Toy and Game Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5944', 'Jewelry, Watch, Clock, and Silverware Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5943', 'Stationery, Office and School Supply Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5942', 'Book Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5941', 'Sporting Goods Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5940', 'Bicycle Shop-Sales and Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5937', 'Antique Reproduction Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5935', 'Wrecking and Salvage Yard');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5933', 'Pawn Sho');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5932', 'Antique Sho');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5931', 'Used Merchandise and Secondhand Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5921', 'Package Stores--Beer, Wine, and Liquo');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5912', 'Drug Stores and Pharmaci');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5818', 'Large Digital Goods Merchant ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5817', 'Digital Goods – Applications (Excludes Games) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5816', 'Digital Goods – Games ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5815', 'Digital Goods – Media, Books, Movies, Music ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5814', 'Quick Payment Service-Fast Food Restaurant');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5813', 'Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs, Cocktail Lounges, and Discothequ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5812', 'Eating Places and Restaurant');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5811', 'Caterers - Prepare & Deliver');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5735', 'Record Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5734', 'Computer Software Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5733', 'Music Stores-Musical Instruments, Pianos, and Sheet Musi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5732', 'Electronics Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5722', 'Household Appliance Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5719', 'Miscellaneous Home Furnishing Specialty Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5718', 'Fireplaces, Fireplace Screens and Accessories Stores');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5714', 'Drapery, Window Covering, and Upholstery Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5713', 'Floor coverings, Rug');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5712', 'Furniture, Home Furnishings, and Equipment Stores, except Applianc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5699', 'Miscellaneous Apparel and Accessory Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5698', 'Wig & Toupee Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5697', 'Tailors, Seamstresses, Mending, Alterations');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5691', 'Mens and Womens Clothing Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5681', 'Furriers & Fur Shop');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5661', 'Shoe Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5655', 'Sports and Riding Apparel Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5651', 'Family Clothing Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5641', 'Childrens and Infants Wear Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5631', 'Womens Accessory and Specialty Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5621', 'Womens Ready-to-Wear Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5611', 'Mens & Boys Clothing and Accessory Stores');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5599', 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers --Not Elsewhere Classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5598', 'Snowmobile Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5592', 'Motor Home Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5571', 'Motorcycle Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5561', 'Camper, Recreational and Utility Trailer Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5551', 'Boat Dealer');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5542', 'Automated Fuel Dispenser');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5541', 'Service Stations (with or without Ancillary Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5533', 'Automotive Parts and Accessories Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5532', 'Automotive Tire Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5531', 'Auto and Home Supply Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5521', 'Car and Truck Dealers (Used)- Sales, Service, Repairs, Parts, and Leasin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5511', 'Car and Truck Dealers (New and Used)- Sales, Service, Repairs, Parts, and Leasin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5499', 'Miscellaneous Food Stores-Convenience Stores and Specialty Market');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5462', 'Bakeri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5451', 'Dairy Product Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5441', 'Candy, Nut, and Confectionary Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5422', 'Freezer & Locker Meat Provision');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5411', 'Grocery Stores and Supermarket');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5399', 'Miscellaneous General Merchandis');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5331', 'Variety Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5311', 'Department Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5310', 'Discount Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5309', 'Duty Free Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5300', 'Wholesale Club with or without membership fe');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5271', 'Mobile Home Deal');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5261', 'Nurseries and Lawn and Garden Supply Stores');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5251', 'Hardware Stores, Equipment Utilities Regulat');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5231', 'Glass, Paint, and Wallpaper Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5211', 'Lumber & Building Materials Stor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5200', 'Home Supply Warehous');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5199', 'Non-durable Goods Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5198', 'Paints, Varnishes and Supplies (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5193', 'Florist Suppliers, Nursery Stock & Flowers (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5192', 'Books, Periodicals and Newspapers (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5172', 'Petroleum and Products (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5169', 'Chemicals and Allied Products Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5139', 'Commercial Footwear (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5137', 'Mens, Womens and Childrens Uniforms (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5131', 'Piece Goods, Notions and Other Dry Goods (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5122', 'Drugs, Drug Proprietarys, and Druggists Sundri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5111', 'Stationery, Office Supplies, and Printing and Writing Pap');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5099', 'Durable Goods Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5094', 'Precious Stones, Metals, Watches and Jewelry (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5085', 'Industrial Supplies Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5074', 'Plumbing and Heating Equipment and Supplies (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5072', 'Hardware, Plumbing, Heat Equipment and Supplies (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5065', 'Electrical Parts and Equipment (Business to Business MCC)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5051', 'Metal Service Centers and Offices (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5047', 'Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Suppli');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5046', 'Commercial Equipment Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5045', 'Computers, Computer Peripheral Equipment, and Softwar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5044', 'Photographic, Photocopy, Microfilm Equipment and Supplies (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5039', 'Construction Materials Not Elsewhere Classified (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5021', 'Office Furniture (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('5013', 'Motor Vehicle Supplies and New Parts (Business to Business MCC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4900', 'Utilities-Electric, Gas, Water, and Sanitar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4899', 'Cable, Satellite, and Other Pay Television and Radio Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4829', 'Quasi Cash - Money Transf');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4821', 'Telegraph Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4816', 'Computer Network/Information Services and other Online Services such as electronic bulletin board, e-mail, web site hosting services, or Internet acces');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4815', 'Monthly Summary Telephone Charg');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4814', 'Telecommunication Services, Including Local and Long Distance Calls, Credit Card Calls, Call Through Use of Magnetic-Strip-Reading Telephones, and Fax Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4813', 'Special Telecom Merchan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4812', 'Telecommunication Equipment and Telephone Sales');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4789', 'Transportation Services-not elsewhere classifi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4784', 'Bridge and Road Fees, Toll');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4761', 'Telemarketing of Travel Related Services and Vitamin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4723', 'Package Tour Operators (Germany Only');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4722', 'Travel Agenci');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4582', 'Airports, Flying Fields, and Airport Terminals');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4511', 'Airlines and Air Carrier');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4468', 'Marinas, Marine Service, and Suppli');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4457', 'Boat Rentals and Leasin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4411', 'Steamship and Cruise Lin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4225', 'Public Warehousing-Farm products, Refrigerated Goods, Household Goods, and Storag');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4215', 'Courier Services-Air and Ground, and Freight Forwarders');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4214', 'Motor Freight Carriers and Trucking-Local and Long Distance, Moving & Storage Companies, and Local Deliver');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4131', 'Bus Lines, includes Charters/Tour Bus');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4121', 'Taxicabs and Limousin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4119', 'Ambulance Servic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4112', 'Passenger Rail (train');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4111', 'Local and Suburban Commuter Passenger Transportation, including Ferri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('4011', 'Railroad');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3831', 'Waldor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3830', 'Park Plaza Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3829', 'Country Inn by Carlso');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3828', 'Cosmopolitan of Las Vega');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3827', 'Galt Hous');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3826', 'Autograph');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3825', 'Vdar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3824', 'Ari');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3823', 'Grand Sierra Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3822', 'Crosslan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3821', 'Caribe Royal');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3820', 'Jumeirah Essex Hous');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3819', 'Oxford Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3818', 'Mainstay Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3817', 'Affini');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3816', 'Home2 Suites');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3815', 'Holiday Inn Nickelodeo');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3814', 'The Roosevelt Hotel N');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3813', 'Hotel Indig');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3812', 'Hyatt Plac');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3811', 'Premier Travel In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3810', 'La Costa Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3808', 'LXR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3807', 'Elemen');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3802', 'The Palace Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3801', 'Wilderness Hotel and Golf Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3800', 'Homestea');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3799', 'Hale Koa Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3798', 'Embassy Vacation Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3797', 'Atlantic City Hilto');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3796', 'Peppermill Hotel Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3795', 'Paris Las Vegas Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3794', 'Grand Casino Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3793', 'The Flamingo Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3792', 'Claridge Casino Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3791', 'Staybridge Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3790', 'Raffles Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3789', 'Smugglers Notch Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3788', 'Ala Moana Hotel / Ala Moana Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3787', 'Caribe Royale Resort Suites & Villa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3786', 'Ohana Hotel of Hawai');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3785', 'Outrigger Hotels and Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3784', 'First Hospitality Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3783', 'Town and Country Resort and Convention Cent');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3782', 'Rosen Hotels & Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3781', 'Patricia Grand Resort Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3780', 'Disney Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3779', 'W Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3778', 'Four Points Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3777', 'Mandalay Bay Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3776', 'Nevele Grande Resort and Country Clu');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3775', 'Sands Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3774', 'New York-New York Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3773', 'The Venetian Resort Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3772', 'Nemacolin Woodland');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3771', 'Caesars Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3770', 'SpringHill Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3769', 'Stratosphere Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3768', 'Silver Star Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3767', 'Main Street Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3766', 'Fremont Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3765', 'Bellagi');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3764', 'Beau Rivage Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3763', 'Chateau Elan Winery and Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3762', 'Whisky Petes Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3761', 'Primadonna Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3760', 'Halekulani Hotel/Waikiki Parc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3759', 'The Orchid at Mauna Lani');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3758', 'Kahala Mandarion Oriental Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3757', 'Canyon Ranc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3755', 'The Homestea');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3754', 'Amelia Island Plantatio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3753', 'Greenbriar Resorts');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3752', 'Peabody Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3751', 'Homewood Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3750', 'Crown Plaza Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3749', 'The Beverly Hills Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3748', 'Wellesley Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3747', 'ClubCorp/ClubResorts');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3746', 'The Eliot Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3745', 'St. Regis Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3744', 'Carefree Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3741', 'Millennium Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3740', 'Towneplace Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3739', 'Woodside Hotels & Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3738', 'Tropicana Resort & Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3737', 'Riviera Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3736', 'Colorado Belle/Edgewater Resor');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3735', 'Master Economy Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3734', 'Harvey/Bristol Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3732', 'Opryland Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3731', 'Harrahs Hotels and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3730', 'MGM Grand Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3729', 'John Ascuagas Nugg');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3728', 'Ballys Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3727', 'Broadmoor Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3726', 'Rio Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3725', 'SeaPines Plantatio');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3724', 'Inter Nor Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3723', 'Rica Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3722', 'Wyndham Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3721', 'Hilton Conrad Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3720', 'Southern Sun Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3719', 'Protea Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3718', 'Karos Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3717', 'City Lodge Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3716', 'Carlton Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3715', 'Fairfield In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3714', 'Four Seasons Hotels-Aust');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3713', 'Quality Pacific Hot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3712', 'Buffalo Bills Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3711', 'Flag Inns (Australia');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3710', 'The Ritz Carlton Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3709', 'Super 8 Motel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3708', 'Virgin River Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3707', 'Shoneys In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3706', 'Shilo In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3705', 'Sandman In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3704', 'Royce Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3703', 'Residence In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3702', 'The Registry Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3701', 'La Mansion Del Ri');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3700', 'Motel ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3699', 'Midway Motor Lodg');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3698', 'Harley Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3697', 'Fairfield Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3696', 'Excel In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3695', 'Embassy Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3694', 'Economy Inns of America');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3693', 'Drury In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3692', 'Doubletr');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3691', 'Dillon In');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3690', 'Courtyard Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3689', 'Consort Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3688', 'Compri Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3687', 'Clarion Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3686', 'Suisse Chal');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3685', 'Budgetel Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3684', 'Budget Hosts Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3683', 'Bradbury Suit');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3682', 'Sahara Hotel and Casin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3681', 'Adams Mark Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3680', 'Hoteis Otha');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3679', 'Silver Legacy Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3678', 'Cumulus Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3677', 'Climat de France Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3676', 'Monte Carlo Hotel and Casino ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3675', 'Interhotel CEDOK');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3674', 'Rantasipi Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3673', 'IBUSZ Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3672', 'Campanile Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3671', 'Arctia Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3670', 'Arcade Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3669', 'Eldorado Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3668', 'Maritim Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3667', 'Luxor Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3666', 'Stakis Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3665', 'Hampton Inn Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3664', 'Flag Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3663', 'Hoteles El Presidente');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3662', 'Circus Circus Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3661', 'Metropole Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3660', 'Knights Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3659', 'Taj Hotels International ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3658', 'New Otani Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3657', 'Oberoi Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3656', 'Sara Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3655', 'Scandic Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3654', 'Loews Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3653', 'Penta Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3652', 'Embassy Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3651', 'Imperial London Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3650', 'Red Roof Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3649', 'Radisson');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3648', 'De Vere Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3647', 'Husa Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3646', 'Swallow Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3645', 'Queens Moat Houses ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3644', 'EconoLodges');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3643', 'Steigenberger Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3642', 'Novotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3641', 'Sofitel Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3640', 'Hyatt Motels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3639', 'Mount Charlotte Thistle ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3638', 'Howard Johnson');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3637', 'Ramada Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3636', 'Sarova Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3635', 'Reso Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3634', 'Swissotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3633', 'Rank Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3632', 'The Phoenician');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3631', 'Sleep Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3630', 'Extended Stay Deluxe');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3629', 'Dan Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3628', 'Excalibur Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3627', 'Extended Stay America');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3626', 'Studio Plus');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3625', 'Hotel Universale');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3624', 'Lady Luck Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3623', 'Dorint Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3622', 'Merlin Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3621', 'Extended Stay');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3620', 'Binions Horseshoe Club ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3619', 'Aloft');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3618', 'Great Wolf');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3617', 'Americas Best Value Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3615', 'Travelodge Motels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3614', 'Americinn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3613', 'Microtel Inns & Suites');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3612', 'Movenpick Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3611', 'C MON INN');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3610', 'Gaylord Texan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3609', 'Gaylord Palms');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3608', 'Gaylord Opryland');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3607', 'Fountainebleau Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3606', 'Jefferson Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3605', 'Jurys Doyle Hotel Group');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3604', 'Hilton Garden Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3603', 'Noahs Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3602', 'Hudson Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3601', 'Trade Winds Resorts');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3600', 'Saddlebrook Resort - Tampa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3599', 'Pannonia Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3598', 'Regent International Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3597', 'Riverside Resort and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3596', 'Wynn Las Vegas');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3595', 'Hospitality Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3594', 'Arizona Biltmore');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3593', 'Cunard Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3592', 'Omni Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3591', 'Sonesta Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3590', 'Fairmont Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3589', 'Doral Golf Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3588', 'Helmsley Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3587', 'Doral Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3586', 'Sokos Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3585', 'Hungar Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3584', 'Princess Hotels International');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3583', 'Radisson BLU');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3582', 'California Hotel and Casino ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3581', 'Delta Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3580', 'Hotel Del Coronado');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3579', 'Hotel Mercure');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3578', 'Frankenmuth Bavarian');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3577', 'Mandarin Oriental Hotel ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3576', 'La Quinta Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3575', 'Vagabond Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3574', 'Venture Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3573', 'Sandman Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3572', 'Miyako Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3571', 'Grand Wailea Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3570', 'Forum Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3569', 'Tribeca Grand Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3568', 'Ladbroke Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3567', 'Soho Grand Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3566', 'Garden Place Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3565', 'Relax Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3564', 'Sams Town Hotel and Casino ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3563', 'Journeys End Motels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3562', 'Comfort Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3561', 'Golden Nugget');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3560', 'Aladdin Resort and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3559', 'Candlewood Suites');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3558', 'Jolly Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3557', 'Manhattan East Suite Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3556', 'Barton Creek Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3555', 'Treasure Island Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3554', 'Pinehurst Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3553', 'Park Inn by Radisson');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3552', 'Coast Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3551', 'Mirage Hotel and Casino');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3550', 'Regal 8 Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3549', 'Auberge des Governeurs');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3548', 'Hotels Melia');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3546', 'Hotel Sierra');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3545', 'Shangri-La International');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3544', 'Cigna Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3543', 'Four Seasons');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3542', 'Royal Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3541', 'Hotel Okura');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3540', 'Iberotel Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3539', 'Summerfield Suites Hotel');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3538', 'Concorde Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3537', 'ANA Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3536', 'AMFAC Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3535', 'Hilton International ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3534', 'Southern Pacific');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3533', 'Hotel Ibis');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3532', 'Royal Kona Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3531', 'Kauai Coconut Beach Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3530', 'Renaissance Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3529', 'CP (Canadian Pacific) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3528', 'Red Lion Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3527', 'Downtowner Passport');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3526', 'Prince Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3525', 'Dunfey Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3524', 'WelcomGroup Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3523', 'Peninsula Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3522', 'Tokyo Group');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3521', 'Royal Lahaina Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3520', 'Meridien Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3519', 'Pullman International Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3518', 'Sol Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3517', 'Americana Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3516', 'LaQuinta Motor Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3515', 'Rodeway Inn');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3514', 'Amerisuites');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3513', 'Westin');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3512', 'Intercontinental Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3511', 'Arabella Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3510', 'Days Inn Colonial Resort');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3509', 'Marriott');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3508', 'Quality Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3507', 'Friendship Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3506', 'Golden Tulip Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3505', 'Forte Hotels');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3504', 'Hilton');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3503', 'Sheraton');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3502', 'Best Western Hotels ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3501', 'Holiday Inns');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3441', 'Advantage Rent A Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3439', 'Millville Rent-a-Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3438', 'Interenet Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3436', 'Autohansa Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3435', 'Value Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3434', 'USA Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3433', 'Ugly Duckling R-A-C ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3432', 'Reserve Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3431', 'Replacement Rent-a-Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3430', 'Major Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3429', 'Insurance Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3428', 'Carey Rent-a-Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3427', 'Avon Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3425', 'Automate Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3423', 'Avcar Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3421', 'Allstate Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3420', 'ANSA International ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3412', 'A-1 R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3409', 'General Rent-a-Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3405', 'Enterprise R-A-C ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3400', 'Auto Host Car Rentals');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3398', 'Econo Car R-A-C ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3396', 'Tilden R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3395', 'Thrify Car Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3394', 'Kemwell Group R-A-C ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3393', 'National Car Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3391', 'Europe by Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3390', 'Dollar R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3389', 'Avis R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3388', 'Merchants Rent-A-Car, Inc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3387', 'Alamo Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3386', 'Showcase Rental Cars');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3385', 'Tropical R-A-C ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3381', 'Europ Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3380', 'Triangle Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3376', 'Ajax R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3374', 'Accent Rent-A-Car');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3370', 'Rent-a-Wreck');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3368', 'Holiday R-A-C');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3366', 'Budget Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3364', 'Agency Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3362', 'Altra Auto Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3361', 'Airways Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3360', 'Snappy Car Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3359', 'Payless Car Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3357', 'Hertz');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3355', 'SIXT Car Rental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3354', 'Action Auto Rental ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3353', 'Brooks Rent a Car ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3352', 'American International');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3351', 'Affiliated Auto Rental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3299', 'Wideroes Flyveselskap');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3298', 'Air Mauritius');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3297', 'Tarom Romanian Air Transport');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3296', 'Air Berlin-AIRBERLIN');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3295', 'Kenya Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3294', 'Ethiopian Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3293', 'Ecuatoriana');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3292', 'Cyprus Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3291', 'Ariana Afghan');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3287', 'Aero Coach Aviation');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3286', 'Aero Nicaraguensis');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3285', 'AeroPeru');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3282', 'Air Djibouti');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3280', 'Air Jamaica');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3279', 'Air LA');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3277', 'Air Madagascar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3276', 'Air Midwest');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3275', 'Air Nevada');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3268', 'Air Pacific');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3267', 'Air Panama International ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3266', 'Air Seychelles');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3263', 'Aero Servicio Carabobo');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3261', 'Air China');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3260', 'Spirit Airlines - SPIRIT');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3256', 'Alaska Airlines Inc.');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3252', 'ALM-Antilean Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3248', 'Tam Airlines - TAM');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3247', 'Gol Airlines - GOL');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3246', 'Ryan Air - RYANAIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3245', 'Easy Jet - EASYJET');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3243', 'Austrian Air Service ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3242', 'Avensa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3241', 'Aviateca (Guatemala) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3240', 'Bahamasair');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3239', 'Bar Harbor Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3236', 'Air Arabia Airlines - Air Arab');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3234', 'CARIBAIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3231', 'SAHSA');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3229', 'SAETA');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3228', 'Cayman Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3226', 'Skyways  Air- SKYWAYS');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3223', 'Comair');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3222', 'Command Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3221', 'Transportes Aeros Mil ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3220', 'Compania Faucett');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3219', 'Copa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3217', 'CSA-Ceskoslovenske Aeroln');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3213', 'Malmo Aviation - MALMO AV');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3212', 'Dominicana de Aviacion');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3211', 'Norwegian Air Shuttle - NORWEGIANAIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3207', 'Empresa Ecuatoriana');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3206', 'China Eastern Airlines (Abbr: China East Air)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3204', 'Freedom Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3200', 'Guyana Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3199', 'Servicios Aereos Militares');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3198', 'Harbor Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3197', 'Havasu Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3196', 'Hawaiian Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3195', 'Holiday Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3193', 'Indian Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3191', 'Island Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3190', 'Jugoslav Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3188', 'Virgin Express - VIR EXP');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3187', 'LACSA (Costa Rica) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3186', 'LAP (Paraguay)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3185', 'LAV (Venezuela)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3184', 'LIAT');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3183', 'Oman Aviation - OMAN AIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3182', 'LOT (Poland)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3181', 'Malev Hungarian Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3180', 'Westjet Airlines-WESTJET');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3178', 'Mesa Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3177', 'AirTran Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3175', 'Middle East Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3174', 'JetBlue Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3172', 'Nation Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3171', 'Canadian Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3167', 'Aero Continente - AEROCONTINENTE');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3164', 'Norontair');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3161', 'All Nippon Airways ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3159', 'PBA-Provincetwn-Bstn Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3156', 'Go Fly');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3151', 'Air Laire');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3148', 'Air Littoral SA');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3146', 'Luxair');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3144', 'Virgin Atlantic');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3141', 'Seair Alaska');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3136', 'Qatar Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3135', 'Sudan Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3132', 'Frontier Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3131', 'VLM Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3130', 'Sunworld International Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3129', 'Surinam Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3127', 'Taca International');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3125', 'Tan Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3117', 'Venezolana Int de Aviacion ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3112', 'Windward Island');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3111', 'British Midland');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3106', 'Braathens S.A.F.E. (Norway) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3105', 'Piedmont');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3103', 'Garuda (Indonesia)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3102', 'Iberia');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3100', 'Malaysian Airline Sys');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3099', 'Cathay Pacific');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3098', 'Asiana Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3097', 'Spanair (abbreviation: SPANAIR)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3096', 'Air Zimbabwe');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3094', 'Zambia Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3090', 'Uni Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3089', 'Tans Saero');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3087', 'Metro Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3085', 'Midwest Express Airlines, Inc');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3084', 'Eva Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3083', 'Air Afrique');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3082', 'Korean Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3079', 'Jetstar Airways - Jetstar');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3078', 'China Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3077', 'Thai Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3076', 'Aeromexico');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3075', 'Singapore Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3073', 'Air Cal');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3072', 'CEBU PAC');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3071', 'Air British Columbia ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3070', 'Pacific Southwest Airlines (PSA)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3069', 'Sun Country Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3068', 'AIR STANA');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3066', 'Southwest');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3065', 'Airinter (AirInternational)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3064', 'Adria Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3063', 'US Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3062', 'Hapag-Lloyd Express - HLX');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3061', 'Continental');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3060', 'NWA Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3059', 'DBA Airlines-DBA AIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3058', 'Delta');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3057', 'Virgin America – VIR AMER');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3056', 'JetAir');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3055', 'LAB (Bolivia) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3054', 'Ladeco (Chile) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3053', 'AVIACO (Spain) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3052', 'LANAIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3051', 'Austrian Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3050', 'Icelandair');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3049', 'Tunis Air');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3048', 'Royal Air Maroc ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3047', 'THY (Turkey)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3046', 'Cruzeiro do Sul (Bra)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3045', 'Nigeria Airways ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3044', 'Air Lanka');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3043', 'Aer Lingus');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3042', 'FinnAir');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3041', 'Balkan-Bulgarian ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3040', 'GulfAir (Bahrain) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3039', 'Avianca');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3038', 'Kuwait Airways ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3037', 'EgyptAir');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3036', 'VASP (Brazil)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3035', 'TAP (Portugal) ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3034', 'ETIHADAIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3033', 'Ansett Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3032', 'El Al');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3031', 'Olympic Airways');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3030', 'Aerolineas Argentinas ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3029', 'SN Brussels Airlines - SN BRUSSELS');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3028', 'Air Malta');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3027', 'UTA/InterAir');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3026', 'Emirates Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3025', 'Air New Zealand Ltd. ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3024', 'Pakistan International');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3023', 'Mexicana');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3022', 'PAL AIR');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3021', 'Air Algerie');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3020', 'Air India');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3018', 'Varig (Brazil)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3017', 'South African Airway ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3016', 'SAS');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3015', 'SWISS');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3014', 'Saudi Arabian Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3013', 'Alitalia');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3012', 'Qantas');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3011', 'AeroFlot');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3010', 'KLM');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3009', 'Air Canada');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3008', 'Lufthansa');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3007', 'Air France');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3006', 'Japan Air Lines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3005', 'British Airways ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3004', 'Dragon Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3003', 'Eurofly Airlines');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3002', 'Pan American');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3001', 'American Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('3000', 'United Airlines ');
INSERT INTO public.mc_codes (code, program_type) VALUES ('2842', 'Specialty Cleaning, Polishing and Sanitation Preparations (Business to Business MCC)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('2791', 'Typesetting, Plate Making and Related Services (Business to Business MCC)');
INSERT INTO public.mc_codes (code, program_type) VALUES ('2741', 'Miscellaneous Publishing and Printing Services');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1799', 'Special Trade Contractor - Not Elsewhere Classified');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1771', 'Contractors, Concrete');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1761', 'Roof, Siding, and Sheet Metal Work Contractors');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1750', 'Carpentry');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1740', 'Masonry, Stonework, Tile Setting, Plastering, Insulation Contractors');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1731', 'Electrical Contractors');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1711', 'Heating, Plumbing, Air Conditioning Contractors');
INSERT INTO public.mc_codes (code, program_type) VALUES ('1520', 'General Contractor/Residential Building');
